alias ol-doc-make='docker run --rm -v $PWD:/data -w /data registry.gitlab.objectif-libre.com/apps/doc-tools make'
alias ol-slides-bootstrap='docker run -ti --rm -v $PWD:/data -w /data registry.gitlab.objectif-libre.com/apps/doc-tools ol-slides-bootstrap'
alias ol-doc-bootstrap='docker run -ti --rm -v $PWD:/data -w /data registry.gitlab.objectif-libre.com/apps/doc-tools ol-doc-bootstrap'
alias oldocs-make='docker run --rm -v $PWD:/data -w /data registry.gitlab.objectif-libre.com/apps/doc-tools:old make'
alias ol-kubeval='docker container run --rm -v $PWD:/data -w /data registry.gitlab.objectif-libre.com/ol/dockerfiles/formation-ci/kubeval gen_junit.sh'
alias ol-doc-linkcheck='docker container run --rm -v $PWD:/data -w /data registry.gitlab.objectif-libre.com/ol/dockerfiles/formation-ci/builder make SPHINXBUILDER=linkcheck'
alias ol-doc-make-new='docker container run --rm -v $PWD:/data -w /data registry.gitlab.objectif-libre.com/ol/dockerfiles/formation-ci/builder:factorized_ci make -f /Makefile'
